// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UserSettings {
    "source_lang": string;
    "target_lang": string;
    "selected_device": number;
    "subtitle_mounted": boolean;
    "history_keyword": string;
    "history_date_from": string;
    "history_date_to": string;

    /** Creates a new UserSettings instance. */
    constructor($$source: Partial<UserSettings> = {}) {
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("selected_device" in $$source)) {
            this["selected_device"] = 0;
        }
        if (!("subtitle_mounted" in $$source)) {
            this["subtitle_mounted"] = false;
        }
        if (!("history_keyword" in $$source)) {
            this["history_keyword"] = "";
        }
        if (!("history_date_from" in $$source)) {
            this["history_date_from"] = "";
        }
        if (!("history_date_to" in $$source)) {
            this["history_date_to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UserSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserSettings($$parsedSource as Partial<UserSettings>);
    }
}
