// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audio$0 from "./internal/audio/models.js";

/**
 * ListCaptureDevices returns all available capture sources.
 * First entry is system audio (WASAPI loopback), followed by microphone devices.
 */
export function ListCaptureDevices(): $CancellablePromise<audio$0.Device[]> {
    return $Call.ByID(2215179610).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetMicrophoneDevice sets the capture device ID.
 * Use -2 for system audio (WASAPI loopback), -1 for default mic, or specific device ID.
 */
export function SetMicrophoneDevice(deviceID: number): $CancellablePromise<void> {
    return $Call.ByID(3060515759, deviceID);
}

/**
 * StartCapture begins audio capture.
 * Uses micDeviceID set via SetMicrophoneDevice to determine the source.
 */
export function StartCapture(sourceType: string): $CancellablePromise<void> {
    return $Call.ByID(2002208921, sourceType);
}

/**
 * StopCapture stops audio capture.
 */
export function StopCapture(): $CancellablePromise<void> {
    return $Call.ByID(328652407);
}

// Private type creation functions
const $$createType0 = audio$0.Device.createFrom;
const $$createType1 = $Create.Array($$createType0);
