// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ExportRecord {
    "source_text": string;
    "translated_text": string;
    "sequence": number;

    /** Creates a new ExportRecord instance. */
    constructor($$source: Partial<ExportRecord> = {}) {
        if (!("source_text" in $$source)) {
            this["source_text"] = "";
        }
        if (!("translated_text" in $$source)) {
            this["translated_text"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRecord($$parsedSource as Partial<ExportRecord>);
    }
}

export class HistoryDetail {
    "session_id": string;
    "source_lang": string;
    "target_lang": string;
    "duration_seconds": number;
    "summary": string;
    "created_at": string;
    "ended_at"?: string;
    "records": HistoryRecord[];

    /** Creates a new HistoryDetail instance. */
    constructor($$source: Partial<HistoryDetail> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("duration_seconds" in $$source)) {
            this["duration_seconds"] = 0;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("records" in $$source)) {
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDetail {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField7_0($$parsedSource["records"]);
        }
        return new HistoryDetail($$parsedSource as Partial<HistoryDetail>);
    }
}

export class HistoryRecord {
    "id": number;
    "session_id": string;
    "sequence": number;
    "source_text": string;
    "translated_text": string;
    "confidence": number;
    "audio_duration_ms": number;
    "created_at": string;

    /** Creates a new HistoryRecord instance. */
    constructor($$source: Partial<HistoryRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("source_text" in $$source)) {
            this["source_text"] = "";
        }
        if (!("translated_text" in $$source)) {
            this["translated_text"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("audio_duration_ms" in $$source)) {
            this["audio_duration_ms"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryRecord($$parsedSource as Partial<HistoryRecord>);
    }
}

export class HistorySession {
    "id": string;
    "source_lang": string;
    "target_lang": string;
    "status": string;
    "record_count": number;
    "brief"?: string;
    "created_at": string;
    "ended_at"?: string;

    /** Creates a new HistorySession instance. */
    constructor($$source: Partial<HistorySession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("record_count" in $$source)) {
            this["record_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistorySession instance from a string or object.
     */
    static createFrom($$source: any = {}): HistorySession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistorySession($$parsedSource as Partial<HistorySession>);
    }
}

export class TranscriptMsg {
    "seq": number;
    "segment_id": number;
    "revision": number;
    "text": string;
    "is_final": boolean;
    "reason": string;
    "timestamp": number;

    /** Creates a new TranscriptMsg instance. */
    constructor($$source: Partial<TranscriptMsg> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("segment_id" in $$source)) {
            this["segment_id"] = 0;
        }
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("is_final" in $$source)) {
            this["is_final"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscriptMsg instance from a string or object.
     */
    static createFrom($$source: any = {}): TranscriptMsg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranscriptMsg($$parsedSource as Partial<TranscriptMsg>);
    }
}

export class TranslationMsg {
    "seq": number;
    "segment_id": number;
    "revision": number;
    "text": string;
    "is_final": boolean;
    "reason": string;
    "timestamp": number;

    /** Creates a new TranslationMsg instance. */
    constructor($$source: Partial<TranslationMsg> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("segment_id" in $$source)) {
            this["segment_id"] = 0;
        }
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("is_final" in $$source)) {
            this["is_final"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationMsg instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationMsg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationMsg($$parsedSource as Partial<TranslationMsg>);
    }
}

export class UserSettings {
    "source_lang": string;
    "target_lang": string;
    "selected_device": number;
    "subtitle_mounted": boolean;
    "history_keyword": string;
    "history_date_from": string;
    "history_date_to": string;

    /** Creates a new UserSettings instance. */
    constructor($$source: Partial<UserSettings> = {}) {
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("selected_device" in $$source)) {
            this["selected_device"] = 0;
        }
        if (!("subtitle_mounted" in $$source)) {
            this["subtitle_mounted"] = false;
        }
        if (!("history_keyword" in $$source)) {
            this["history_keyword"] = "";
        }
        if (!("history_date_from" in $$source)) {
            this["history_date_from"] = "";
        }
        if (!("history_date_to" in $$source)) {
            this["history_date_to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UserSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserSettings($$parsedSource as Partial<UserSettings>);
    }
}

// Private type creation functions
const $$createType0 = HistoryRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
