// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HistoryDetail {
    "session_id": string;
    "source_lang": string;
    "target_lang": string;
    "duration_seconds": number;
    "summary": string;
    "created_at": string;
    "ended_at"?: string;
    "records": HistoryRecord[];

    /** Creates a new HistoryDetail instance. */
    constructor($$source: Partial<HistoryDetail> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("duration_seconds" in $$source)) {
            this["duration_seconds"] = 0;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("records" in $$source)) {
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDetail {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField6_0($$parsedSource["records"]);
        }
        return new HistoryDetail($$parsedSource as Partial<HistoryDetail>);
    }
}

export class HistoryRecord {
    "id": number;
    "session_id": string;
    "sequence": number;
    "source_text": string;
    "translated_text": string;
    "confidence": number;
    "audio_duration_ms": number;
    "created_at": string;

    /** Creates a new HistoryRecord instance. */
    constructor($$source: Partial<HistoryRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("source_text" in $$source)) {
            this["source_text"] = "";
        }
        if (!("translated_text" in $$source)) {
            this["translated_text"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("audio_duration_ms" in $$source)) {
            this["audio_duration_ms"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryRecord($$parsedSource as Partial<HistoryRecord>);
    }
}

export class HistorySession {
    "id": string;
    "source_lang": string;
    "target_lang": string;
    "status": string;
    "record_count": number;
    "summary"?: string;
    "created_at": string;
    "ended_at"?: string;

    /** Creates a new HistorySession instance. */
    constructor($$source: Partial<HistorySession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("record_count" in $$source)) {
            this["record_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistorySession instance from a string or object.
     */
    static createFrom($$source: any = {}): HistorySession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistorySession($$parsedSource as Partial<HistorySession>);
    }
}

export class TranscriptMsg {
    "text": string;
    "is_final": boolean;
    "timestamp": number;

    /** Creates a new TranscriptMsg instance. */
    constructor($$source: Partial<TranscriptMsg> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("is_final" in $$source)) {
            this["is_final"] = false;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscriptMsg instance from a string or object.
     */
    static createFrom($$source: any = {}): TranscriptMsg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranscriptMsg($$parsedSource as Partial<TranscriptMsg>);
    }
}

export class TranslationMsg {
    "text": string;
    "is_final": boolean;
    "timestamp": number;

    /** Creates a new TranslationMsg instance. */
    constructor($$source: Partial<TranslationMsg> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("is_final" in $$source)) {
            this["is_final"] = false;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationMsg instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationMsg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationMsg($$parsedSource as Partial<TranslationMsg>);
    }
}

// Private type creation functions
const $$createType0 = HistoryRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
