// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSession creates a new translation session on the backend
 */
export function CreateSession(sourceLang: string, targetLang: string, inputType: string): $CancellablePromise<string> {
    return $Call.ByID(4095665835, sourceLang, targetLang, inputType);
}

export function DeleteHistory(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4177947542, sessionID);
}

export function DeleteHistoryBatch(ids: string[]): $CancellablePromise<number> {
    return $Call.ByID(1982723042, ids);
}

/**
 * GetHistory fetches a single history session with all its records
 */
export function GetHistory(sessionID: string): $CancellablePromise<$models.HistoryDetail | null> {
    return $Call.ByID(3803928165, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListHistory fetches paginated session history from the backend
 */
export function ListHistory(offset: number, limit: number): $CancellablePromise<[$models.HistorySession[], number]> {
    return $Call.ByID(2268283967, offset, limit).then(($result: any) => {
        $result[0] = $$createType3($result[0]);
        return $result;
    });
}

/**
 * PauseInterpret pauses the current interpret session without closing the connection
 */
export function PauseInterpret(): $CancellablePromise<void> {
    return $Call.ByID(2397763438);
}

/**
 * ResumeInterpret resumes a paused interpret session
 */
export function ResumeInterpret(): $CancellablePromise<void> {
    return $Call.ByID(4000226251);
}

export function SearchHistory(offset: number, limit: number, keyword: string, dateFrom: string, dateTo: string): $CancellablePromise<[$models.HistorySession[], number]> {
    return $Call.ByID(641781247, offset, limit, keyword, dateFrom, dateTo).then(($result: any) => {
        $result[0] = $$createType3($result[0]);
        return $result;
    });
}

/**
 * SendAudio sends a PCM audio chunk to the backend
 */
export function SendAudio(data: string): $CancellablePromise<void> {
    return $Call.ByID(3279378679, data);
}

/**
 * StartInterpret connects to the backend WebSocket for real-time translation
 */
export function StartInterpret(): $CancellablePromise<void> {
    return $Call.ByID(2067849448);
}

/**
 * StopInterpret ends the translation session
 */
export function StopInterpret(): $CancellablePromise<void> {
    return $Call.ByID(3294272606);
}

export function SummarizeHistory(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(1733707310, sessionID);
}

// Private type creation functions
const $$createType0 = $models.HistoryDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.HistorySession.createFrom;
const $$createType3 = $Create.Array($$createType2);
