// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Load(): $CancellablePromise<$models.UserSettings> {
    return $Call.ByID(3957400160).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Save(settings: $models.UserSettings): $CancellablePromise<void> {
    return $Call.ByID(2704157817, settings);
}

// Private type creation functions
const $$createType0 = $models.UserSettings.createFrom;
