// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function HideMain(): $CancellablePromise<void> {
    return $Call.ByID(2514360940);
}

export function HideSubtitle(): $CancellablePromise<void> {
    return $Call.ByID(1434755013);
}

export function ShowMain(): $CancellablePromise<void> {
    return $Call.ByID(3773652421);
}

export function ShowSubtitle(): $CancellablePromise<void> {
    return $Call.ByID(2730021324);
}

export function ToggleSubtitle(): $CancellablePromise<boolean> {
    return $Call.ByID(3971182765);
}
