// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function HideMain(): $CancellablePromise<void> {
    return $Call.ByID(2090159970);
}

export function HideSubtitle(): $CancellablePromise<void> {
    return $Call.ByID(3761671647);
}

export function SetSubtitleVisible(visible: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(2891776713, visible);
}

export function ShowMain(): $CancellablePromise<void> {
    return $Call.ByID(3582330847);
}

export function ShowSubtitle(): $CancellablePromise<void> {
    return $Call.ByID(1195462466);
}

export function ToggleSubtitle(): $CancellablePromise<boolean> {
    return $Call.ByID(2174180971);
}
