// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportSRT(title: string, records: $models.ExportRecord[]): $CancellablePromise<string> {
    return $Call.ByID(3639243684, title, records);
}

export function ExportTXT(title: string, records: $models.ExportRecord[]): $CancellablePromise<string> {
    return $Call.ByID(3126465719, title, records);
}
