// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ExportRecord {
    "source_text": string;
    "translated_text": string;
    "sequence": number;

    /** Creates a new ExportRecord instance. */
    constructor($$source: Partial<ExportRecord> = {}) {
        if (!("source_text" in $$source)) {
            this["source_text"] = "";
        }
        if (!("translated_text" in $$source)) {
            this["translated_text"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRecord($$parsedSource as Partial<ExportRecord>);
    }
}
