// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AuthState(): $CancellablePromise<$models.AuthUser> {
    return $Call.ByID(2557031078).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ChangePassword(currentPassword: string, newPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2456312838, currentPassword, newPassword);
}

export function CreateSession(sourceLang: string, targetLang: string, inputType: string): $CancellablePromise<string> {
    return $Call.ByID(852100741, sourceLang, targetLang, inputType);
}

export function DeleteHistory(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2127282752, sessionID);
}

export function DeleteHistoryBatch(ids: string[]): $CancellablePromise<number> {
    return $Call.ByID(3578211576, ids);
}

export function GetHistory(sessionID: string): $CancellablePromise<$models.HistoryDetail | null> {
    return $Call.ByID(884844607, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListHistory(offset: number, limit: number): $CancellablePromise<[$models.HistorySession[], number]> {
    return $Call.ByID(58364749, offset, limit).then(($result: any) => {
        $result[0] = $$createType4($result[0]);
        return $result;
    });
}

export function Login(email: string, password: string): $CancellablePromise<$models.AuthUser> {
    return $Call.ByID(2920166472, email, password).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(500262189);
}

export function PauseInterpret(): $CancellablePromise<void> {
    return $Call.ByID(681837408);
}

export function ResumeInterpret(): $CancellablePromise<void> {
    return $Call.ByID(1957558021);
}

export function SearchHistory(offset: number, limit: number, keyword: string, dateFrom: string, dateTo: string): $CancellablePromise<[$models.HistorySession[], number]> {
    return $Call.ByID(2332623437, offset, limit, keyword, dateFrom, dateTo).then(($result: any) => {
        $result[0] = $$createType4($result[0]);
        return $result;
    });
}

export function SendAudio(data: string): $CancellablePromise<void> {
    return $Call.ByID(3326362033, data);
}

export function StartInterpret(): $CancellablePromise<void> {
    return $Call.ByID(2472336190);
}

export function StopInterpret(): $CancellablePromise<void> {
    return $Call.ByID(1786056896);
}

export function SummarizeHistory(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(1670486960, sessionID);
}

// Private type creation functions
const $$createType0 = $models.AuthUser.createFrom;
const $$createType1 = $models.HistoryDetail.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.HistorySession.createFrom;
const $$createType4 = $Create.Array($$createType3);
