package server

import "github.com/gin-gonic/gin"

func (a *Application) registerAdminRoutes(admin *gin.RouterGroup) {
	admin.GET("/users", a.handleListUsers)
	admin.POST("/users", a.handleCreateUser)
	admin.PATCH("/users/:id", a.handleUpdateUser)
	admin.POST("/users/:id/reset-password", a.handleResetUserPassword)
	admin.POST("/legacy-sessions/claim", a.handleClaimLegacySessions)
	admin.GET("/dashboard", a.handleDashboard)
	admin.GET("/governance/report", a.handleGovernanceReport)
	admin.GET("/audit-logs", a.handleListAuditEvents)
	admin.POST("/objects", a.handleUploadObject)
	admin.GET("/objects", a.handleListObjects)
	admin.GET("/objects/usage", a.handleStorageUsage)
	admin.GET("/objects/:id", a.handleGetObject)
	admin.GET("/objects/:id/content", a.handleDownloadObject)
	admin.DELETE("/objects/:id", a.handleDeleteObject)
	admin.POST("/datasets", a.handleCreateDataset)
	admin.GET("/datasets", a.handleListDatasets)
	admin.GET("/datasets/:id", a.handleGetDataset)
	admin.PATCH("/datasets/:id", a.handleUpdateDataset)
	admin.DELETE("/datasets/:id", a.handleDeleteDataset)
	admin.POST("/datasets/:id/items", a.handleAddDatasetItem)
	admin.DELETE("/datasets/:id/items/:item_id", a.handleDeleteDatasetItem)
	admin.POST("/datasets/:id/ready", a.handleMarkDatasetReady)
	admin.POST("/datasets/:id/archive", a.handleArchiveDataset)
	admin.POST("/evaluation-jobs", a.handleCreateEvaluationJob)
	admin.GET("/evaluation-jobs", a.handleListEvaluationJobs)
	admin.GET("/evaluation-jobs/:id", a.handleGetEvaluationJob)
	admin.GET("/evaluation-jobs/:id/results", a.handleListEvaluationResults)
	admin.POST("/evaluation-jobs/:id/cancel", a.handleCancelEvaluationJob)
	admin.POST("/evaluation-jobs/:id/retry", a.handleRetryEvaluationJob)
}
