// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Device {
    "id": number;
    "name": string;

    /**
     * "microphone" | "system_audio"
     */
    "type": string;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Device($$parsedSource as Partial<Device>);
    }
}
