import { FormEvent, useEffect, useState } from "react";
import { Ban, GitCompare, Play, RefreshCw, RotateCcw } from "lucide-react";
import { api } from "../api";
import { Empty, ErrorNotice, formatDate, formatRate, Loading, Modal, PageHeader, Status, SuccessNotice } from "../components";
import type { Dataset, EvaluationJob, EvaluationResult } from "../types";

export default function EvaluationsPage() {
  const [jobs, setJobs] = useState<EvaluationJob[]>([]); const [selected, setSelected] = useState<string>(); const [results, setResults] = useState<EvaluationResult[]>([]);
  const [status, setStatus] = useState(""); const [creating, setCreating] = useState(false); const [creatingAB, setCreatingAB] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = () => { setLoading(true); api.request<{ jobs: EvaluationJob[] }>(`/admin/evaluation-jobs?limit=100${status ? `&status=${status}` : ""}`).then((data) => setJobs(data.jobs)).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); };
  const loadResults = (id: string) => api.request<{ results: EvaluationResult[] }>(`/admin/evaluation-jobs/${id}/results?limit=100`).then((data) => setResults(data.results)).catch((reason) => setError(reason.message));
  useEffect(load, [status]); useEffect(() => { if (selected) loadResults(selected); else setResults([]); }, [selected]);
  const cancel = async (id: string) => { try { await api.request(`/admin/evaluation-jobs/${id}/cancel`, { method: "POST" }); setSuccess("任务已取消"); load(); } catch (reason) { setError((reason as Error).message); } };
  const retry = async (id: string) => { try { await api.request(`/admin/evaluation-jobs/${id}/retry`, { method: "POST" }); setSuccess("任务已重新进入队列"); load(); } catch (reason) { setError((reason as Error).message); } };
  const current = jobs.find((job) => job.id === selected);
  return <>
    <PageHeader title="评测任务" description="ASR、CER/WER 与人工分段对比" actions={<><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="任务状态"><option value="">全部状态</option><option value="queued">排队</option><option value="running">运行中</option><option value="succeeded">成功</option><option value="completed_with_errors">部分失败</option><option value="failed">失败</option><option value="dead_lettered">死信</option><option value="cancelled">已取消</option></select><button className="icon-button" title="刷新" onClick={load}><RefreshCw size={18} /></button><button className="button-secondary" onClick={() => setCreatingAB(true)}><GitCompare size={17} />创建 A/B 对比</button><button className="button" onClick={() => setCreating(true)}><Play size={17} />创建任务</button></>} />
    {error && <ErrorNotice message={error} onClose={() => setError("")} />}{success && <SuccessNotice message={success} />}
    {loading ? <Loading /> : jobs.length === 0 ? <Empty title="没有评测任务" description="为已发布数据集创建离线评测。" /> : <section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>任务</th><th>状态</th><th>语言</th><th>进度</th><th>尝试</th><th>成功 / 失败</th><th>ASR CER</th><th>分段 CER</th><th>分段 F1</th><th>创建时间</th><th aria-label="操作" /></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className={selected === job.id ? "active-row" : ""} onClick={() => setSelected(job.id)}><td className="mono">{job.id.slice(0, 8)}</td><td><Status value={job.status} /></td><td>{job.dataset_language}</td><td><span className="progress"><i style={{ width: `${job.progress * 100}%` }} /></span>{Math.round(job.progress * 100)}%</td><td>{job.attempt_count} / {job.max_attempts}</td><td>{job.succeeded_items} / {job.failed_items}</td><td>{formatRate(job.asr_cer)}</td><td>{formatRate(job.segmented_cer)}</td><td>{job.segment_evaluable ? formatRate(job.segment_f1) : "-"}</td><td>{formatDate(job.created_at)}</td><td>{["queued", "running"].includes(job.status) ? <button className="icon-button danger" title="取消任务" onClick={(event) => { event.stopPropagation(); cancel(job.id); }}><Ban size={16} /></button> : ["failed", "dead_lettered"].includes(job.status) ? <button className="icon-button" title="重新进入队列" onClick={(event) => { event.stopPropagation(); retry(job.id); }}><RotateCcw size={16} /></button> : null}</td></tr>)}</tbody></table></div></section>}
    {current && <section className="panel result-panel"><div className="panel-heading"><div><h2>逐条结果</h2><p>{current.id} · 数据集修订 r{current.dataset_revision}</p></div><Status value={current.status} /></div>{results.length === 0 ? <Empty title="暂无结果" description={current.status === "running" ? "任务运行中，刷新后查看。" : "该任务没有可展示的逐条结果。"} /> : <div className="result-list">{results.map((result) => <details key={result.id}><summary><span>#{result.sequence}</span><Status value={result.status} /><span>ASR CER {formatRate(result.asr_cer)}</span><span>分段 F1 {result.segment_evaluable ? formatRate(result.segment_f1) : "-"}</span></summary><div className="comparison-grid"><TextBlock label="参考文本" text={result.reference_text} /><TextBlock label="ASR 原文" text={result.asr_text} /><TextBlock label="分段文本" text={result.segmented_text} /></div>{result.error_message && <ErrorNotice message={result.error_message} />}</details>)}</div>}</section>}
    {creating && <CreateEvaluationModal onClose={() => setCreating(false)} onDone={(id) => { setCreating(false); setSuccess("评测任务已进入队列"); load(); setSelected(id); }} onError={setError} />}
    {creatingAB && <CreateABModal onClose={() => setCreatingAB(false)} onDone={() => { setCreatingAB(false); setSuccess("A/B 实验已进入队列"); load(); }} onError={setError} />}
  </>;
}

function CreateABModal({ onClose, onDone, onError }: { onClose: () => void; onDone: () => void; onError: (message: string) => void }) {
  const [datasets, setDatasets] = useState<Dataset[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { api.request<{ datasets: Dataset[] }>("/admin/datasets?status=ready&limit=100").then((data) => setDatasets(data.datasets)).catch((reason) => onError(reason.message)); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await api.request("/admin/evaluation-runs", { method: "POST", body: JSON.stringify({ dataset_id: form.get("dataset_id"), max_runes: Number(form.get("max_runes")), max_duration_ms: Number(form.get("max_duration_ms")), soft_commit_delay_ms: Number(form.get("soft_commit_delay_ms")) }) }); onDone(); } catch (reason) { onError((reason as Error).message); setBusy(false); } };
  return <Modal title="创建 A/B 对比" onClose={onClose}><form className="form" onSubmit={submit}><label>已发布数据集<select name="dataset_id" required autoFocus><option value="">选择数据集</option>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.name} · {dataset.language} · {dataset.item_count} 条</option>)}</select></label><p className="form-hint">系统会自动使用同一批 ASR 结果执行“启用分段器”和“关闭分段器”两个变体。</p><div className="form-row"><label>最大字符数<input name="max_runes" type="number" min={1} max={500} defaultValue={40} /></label><label>最大时长 ms<input name="max_duration_ms" type="number" min={100} max={60000} defaultValue={5000} /></label></div><label>软提交延迟 ms<input name="soft_commit_delay_ms" type="number" min={10} max={10000} defaultValue={300} /></label><div className="form-actions"><button type="button" className="button-secondary" onClick={onClose}>取消</button><button className="button" disabled={busy || !datasets.length}>开始双测</button></div></form></Modal>;
}

function TextBlock({ label, text }: { label: string; text: string }) { return <div className="text-block"><span>{label}</span><p>{text || "-"}</p></div>; }

function CreateEvaluationModal({ onClose, onDone, onError }: { onClose: () => void; onDone: (id: string) => void; onError: (message: string) => void }) {
  const [datasets, setDatasets] = useState<Dataset[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { api.request<{ datasets: Dataset[] }>("/admin/datasets?status=ready&limit=100").then((data) => setDatasets(data.datasets)).catch((reason) => onError(reason.message)); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const payload = { dataset_id: form.get("dataset_id"), segmenter_enabled: form.get("segmenter_enabled") === "on", max_runes: Number(form.get("max_runes")), max_duration_ms: Number(form.get("max_duration_ms")), soft_commit_delay_ms: Number(form.get("soft_commit_delay_ms")) }; try { const job = await api.request<EvaluationJob>("/admin/evaluation-jobs", { method: "POST", body: JSON.stringify(payload) }); onDone(job.id); } catch (reason) { onError((reason as Error).message); setBusy(false); } };
  return <Modal title="创建评测任务" onClose={onClose}><form className="form" onSubmit={submit}><label>已发布数据集<select name="dataset_id" required autoFocus><option value="">选择数据集</option>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.name} · {dataset.language} · {dataset.item_count} 条</option>)}</select></label><label className="checkbox"><input name="segmenter_enabled" type="checkbox" defaultChecked />启用分段器</label><div className="form-row"><label>最大字符数<input name="max_runes" type="number" min={1} max={500} defaultValue={40} /></label><label>最大时长 ms<input name="max_duration_ms" type="number" min={100} max={60000} defaultValue={5000} /></label></div><label>软提交延迟 ms<input name="soft_commit_delay_ms" type="number" min={10} max={10000} defaultValue={300} /></label><div className="form-actions"><button type="button" className="button-secondary" onClick={onClose}>取消</button><button className="button" disabled={busy || !datasets.length}>进入队列</button></div></form></Modal>;
}
